import { StyleSheet } from 'react-native';
import Colors from '../../../assets/theme/Colors';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../helper/Metrics';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: Colors.White,
  },
  markerContainer: {
    alignItems: 'center',
  },
  bubble: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: horizontalScale(10),
    borderColor: '#DADADA',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    justifyContent: 'space-between',
    height: 60,
  },
  emthyView: {
    width: horizontalScale(65),
  },
  username: {
    fontSize: moderateScale(15),
    color: Colors.Black,
    fontWeight: '600',
    marginRight: 6,
  },
  time: {
    fontSize: moderateScale(13),
    color: Colors.Black,
    fontWeight: '500',
    marginTop: 2,
  },
  avatar: {
    width: horizontalScale(65),
    height: horizontalScale(65),
    borderRadius: horizontalScale(14),
  },
  avatarOverlay: {
    position: 'absolute',
    right: -10,
    backgroundColor: Colors.White,
    justifyContent: 'center',
    alignItems: 'center',
    height: horizontalScale(70),
    width: horizontalScale(70),
    borderRadius: horizontalScale(14),
  },
  pointer: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'white',
    marginTop: -1,
  },
  mapOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '15%',
    zIndex: 10,
  },
  filterBtn: {
    backgroundColor: Colors.White,
    borderRadius: 30,
    width: 55,
    height: 55,
    position: 'absolute',
    zIndex: 10,
    bottom: 20,
    left: 20,
    borderWidth: 1,
    borderColor: Colors.Black10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    marginTop: verticalScale(150),
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    width: '85%',
    position: 'absolute',
    alignSelf: 'center',
    top: verticalScale(20),
  },
  modalTitle: {
    fontSize: moderateScale(18),
    color: 'black',
    marginBottom: verticalScale(10),
    fontWeight: '700',
  },
  subTitle: {
    fontSize: moderateScale(12),
    color: '#696969',
    fontWeight: '500',
    marginTop: -6,
    marginBottom: verticalScale(10),
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '95%',
    marginBottom: verticalScale(6),
  },
  labelText: {
    fontSize: moderateScale(12),
    color: '#888',
    fontWeight: '500',
  },
  valueText: {
    marginTop: verticalScale(8),
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: Colors.Primary,
  },
  applyButton: {
    backgroundColor: '#9962FF',
    borderRadius: 20,
    paddingHorizontal: horizontalScale(30),
    paddingVertical: verticalScale(8),
    marginTop: verticalScale(40),
    width: '90%',
  },
  applyButtonText: {
    color: 'white',
    fontSize: moderateScale(16),
    fontWeight: '700',
    textAlign: 'center',
  },
});
